### Introduction to Python
#### Date: Sep 06,2023
#### Submission must be made through Github
You are required to complete all tasks correctly (or almost correctly) . You are free to use any material (lecture, Stackoverflow etc.) except full solutions but you should first try to figure them out on your own. We use an nbgrader for partially autograding the assignments. Please DO NOT delete or copy cells. You can add new cells but your solutions should go into the designated cells. 

In [ ]:
#MIRIAM NANTEZA
#REG.NO: 2023/HD05/04706U
#2300704706

`range()` practice

1 . Print the numbers between 60 and 69 inclusive.

In [1]:
for i in range(60,70):
    print(i)

60
61
62
63
64
65
66
67
68
69


2 . Read numbers until 0 and print their mean and standard deviation without using a list.

In [2]:
import numpy as np

#mean
my_arr = np.array([1,2,3,4])
print(np.mean(my_arr))

2.5


In [ ]:
#Standard Deviation
sum_of_squares = 0
total = 0
counter = 0

while(True):
    number = int(input("Enter a number: "))
    if number == 0:
        break
    sum_of_squares += (number **2)
    total += number
    counter += 1
    
mean = total / counter
print(f"Mean is: {str(mean)}")

standard_dev = ((sum_of_squares/counter) - mean**2)**(1/2)
print(f"Standard deviation: {standard_dev}")
        


##### Lists
3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

In [ ]:
l = [2, 3, -2, -7, 0, 2, 3]

for num in l:
    if num % 2 != 0:
        print(num, end=" ")

##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

In [ ]:
# Function to print the first N prime numbers
def is_prime(n):
    if n<=1:
        return False
    for i in range(2, n):
        if(n%i==0):
            return False
    return True

def get_n_primes(N):
    prime_num = []
    count = 0
    num = 2
    
    while count < N:
        if is_prime(num):
            prime_num.append(num)
            count += 1
        num += 1
    print(prime_num)

N = int(input("Enter any number: "))
get_n_primes(N)
    

In [ ]:
assert(get_n_primes(3) == [2, 3, 5])
assert(get_n_primes(0) == [])

5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.

 The Fibonacci series is defined as:

$$
F_n = F_{n-1} + F_{n-2} \text{ for } n>1\\
F_0 = 0\\
F_1 = 1
$$

The first few elements of the Fibonacci series are 0, 1, 1, 2, 3, 5, 8, 13 etc.

Raise a `ValueError` if $N<0$.


In [ ]:
def get_nth_fibonacci(N):
    try:
        if N < 0:
            raise ValueError("Only positive integers are expected")
        elif N in {0, 1}:
            return N
        elif N == 2:
            return 1
        else:
            return get_nth_fibonacci(N-1) + get_nth_fibonacci(N-2)
    except ValueError:
        return(f"{N} is less than 0")

N = int(input("Enter any number: "))
print(f"{N}th Fibonacci number is: {get_nth_fibonacci(N)}")

In [ ]:
assert(get_nth_fibonacci(0) == 0)
assert(get_nth_fibonacci(1) == 1)
assert(get_nth_fibonacci(2) == 1)
assert(get_nth_fibonacci(5) == 5)
assert(get_nth_fibonacci(7) == 13)

try:
    get_nth_fibonacci(-2)
except ValueError:
    pass
else:
    AssertionError("TEST FAILS. Negative index should raise a ValueError.")

6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.


In [ ]:
def is_odd(n):
    return n % 2 !=0

def is_prime(n):
    if n<=1:
        return False
    for i in range(2, n):
        if(n%i==0):
            return False
    return True

In [ ]:
def filter_list(listz, predicate):
    filtered_list = []
    for i in listz:
        if predicate(i):
            filtered_list.append(i)
    return filtered_list

In [ ]:
l1 = [1, 2, 3, 4, 19, 35, 11]
l2 = [1, 4, 9, 16, 25]
assert(filter_list(l1, is_odd) == [1, 3, 19, 35, 11])
assert(filter_list(l1, is_prime) == [2, 3, 19, 11])
assert(filter_list(l2, is_prime) == [])

7.  Reduce is a function that applies a two argument function against an accumulator and each element in the sequence (from left to right) to reduce it to a single value. If no initial value is provided, the accumulator is initialized with the return value of the function run on the first two elements of the sequence.

```
reduce([1, 2, 3], product) ---> 6
reduce([1, 2, 3], product, accumulator=10) ---> 60
reduce(["foo", "bar"], string_addition) ---> "foobar"
reduce(["foo", "bar"], string_addition, accumulator="hello") ---> "hellofoobar"
```

In [ ]:
def reduce(l1, func, acc=None):
    my_array = l1.copy()
    if acc != None:
        my_array.append(acc)
        return func(my_array)
    return func(my_array)

def product(x):
    return np.product(x)

def add(x):
    return np.sum(x)

def string_len_add(x):
    x = ["foo", "bar", "hello"]
    return sum(map(len, x))
    

In [ ]:
l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

assert(reduce(l1, add) == 7)
assert(reduce(l1, add, 10) == 17)
assert(reduce(l2, string_len_add, 0) == 11)

8. Use your reduce function for the following operations:

##### a. count the number of odd elements in a list of integers,
##### b. find the maximum of a list of integers,
##### c. find the longest string in list of strings.

``` Test your solutions. ```

In [ ]:
#Count the number of odd elements in a list

def count_odd(l1):
    count = 0
    for i in l1:
        if i%2 !=0:
            count += 1
    return count

count_odd_elements = reduce(l1, count_odd)
print(count_odd_elements)

In [ ]:
# Find the maximum in a list of integers
def find_max(l1):
    return max(l1)

maxi = reduce(l1, find_max)
print(maxi)

In [ ]:
#Find longest string in the list of strings

def longest_string(l1):
    return sorted(l1, key=len, reverse=True)[0]

longest_s = reduce(l2, longest_string)
print(longest_s)

9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

For input $A^{N \times M}$, the output should be $D^{N \times N}$ where: $D_{i,j} = L_2 (A_i, A_j)$

In [ ]:
import math

def is_matrix(matrix):
    # Check if its a matrix
    return all(len(row) == len(matrix[0]) for row in matrix)

def transpose(matrix):
    # Compute the transpose of a matrix
    return [[matrix[j][i] for j in range(len(matrix))] for i in range(len(matrix[0]))]

def pairwise_row_distance(matrix):
    N = len(matrix)
    distance_matrix = [[0.0] * N for _ in range(N)]
    
    for i in range(N):
        for j in range(i, N):  
            distance = math.sqrt(sum((a - b) ** 2 for a, b in zip(matrix[i], matrix[j])))
            distance_matrix[i][j] = distance
            distance_matrix[j][i] = distance  # Since it's symmetric
            
    return distance_matrix

In [ ]:
D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])
# should be a matrix
assert is_matrix(D) == True
assert len(D) == 2
assert len(D[0]) == 2
assert D[0][0] == 0
assert abs(D[0][1] - 2.449489742783178) < 1e-3
assert abs(D[1][0] - 2.449489742783178) < 1e-3
assert D[1][1] == 0

# should be symmetric
assert transpose(D) == D

10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.

In [63]:
# OOP
class A:
    def __init__(self, value):
        self.value = value
        
    def print_value(self):
        print("The value is: "+ self.value)

In [64]:
a = A("abc")
a.print_value()

The value is: abc


11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.

In [65]:
class B:
    def __init__(self, this_is_public, this_is_private):
        self.this_is_public = this_is_public
        self.this_is_private = this_is_private
        
B.__dict__

mappingproxy({'__module__': '__main__',
              '__init__': <function __main__.B.__init__(self, this_is_public, this_is_private)>,
              '__dict__': <attribute '__dict__' of 'B' objects>,
              '__weakref__': <attribute '__weakref__' of 'B' objects>,
              '__doc__': None})

In [66]:
b = B(1, 2)
assert b.this_is_public == 1
try:
    b.__this_is_private
    print("This should not happen.")
except AttributeError:
    print("Failed to access private attribute, this is good :)")

Failed to access private attribute, this is good :)


13 . Inheritance

###### Guess the output without running the cell.

In [67]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object)) # True
print(isinstance(b, object)) #True
print(isinstance(a, B)) #False
print(isinstance(b, A)) #True
print(isinstance(d, A)) #True

True
True
False
True
True


In [68]:
print(issubclass(C, object)) #True
print(issubclass(D, B)) #True
print(issubclass(B, D)) #False
print(issubclass(B, B)) #True

True
True
False
True


#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

In [69]:
class Animals():
    def __init__(self, age, number_of_legs):
        self.age = age
        self.number_of_legs = number_of_legs
        
class Sound:
    def make_sound():
        print("Animals have different sounds")
        
class Fur_Color:
    def __init__(self, fur_color):
        self.fur_color = fur_color
        
class Cat(Animals, Sound, Fur_Color):
    def make_sound(self):
        print("Cats make a Meow Meow sound")

class Dog(Animals, Sound, Fur_Color):
    def make_sound(self):
        print("Dogs bark")

class Fish(Animals):
    pass

class Eagle(Animals, Sound):
    def make_sound(self):
        print("Eagles make a piping sound")


In [70]:
try:
    cat = Cat("Fluffy", age=3, fur="white")
    dog = Dog("Cherry", age=1, fur=("white", "brown", "black"))
    fish = Fish("King")
    eagle = Eagle("Bruce", age=2)
    animals = [cat, dog, fish, eagle]
except Exception as e:
    print(f'Could not initialize an animal: {e}')

Could not initialize an animal: Animals.__init__() got multiple values for argument 'age'


#### Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function.

##### Implement standardization for 2D arrays.

Standardization is defined as:

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean of each row and $\rho$ is the standard deviation of each column.

In [80]:
def standardize(X):
    return (X - np.mean(X, axis=0)) / (np.std(X, axis=0))

X_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
X_std

array([[-0.70710678, -0.70710678],
       [ 1.41421356,  1.41421356],
       [-0.70710678, -0.70710678]])

#### Implement normalization for 2D arrays.

Normalization is defined as:

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

In [102]:
def normalize(X):
    min_val = np.min(X)
    max_val = np.max(X)
    
    if max_val - min_val == 0:
        return X 
    
    return (X - min_val) / (max_val - min_val)

X = np.arange(6).reshape(2, 3)
X[1, 2] = -5
print(X)
normalize(X)

[[ 0  1  2]
 [ 3  4 -5]]


array([[0.55555556, 0.66666667, 0.77777778],
       [0.88888889, 1.        , 0.        ]])

In [103]:
answer = np.array(
    [[0., 0., 1.],
     [1., 1., 0.]]
)
X_norm = normalize(X)
assert np.allclose(X_norm, answer)

AssertionError: 